# Project information
site_name: MOH! Documentation
site_description: Documentazione delle app prodotte da RedWingLabs
site_author: RedWing Labs

# Copyright
copyright: Copyright &copy; 2019 - 2020 RWL Srl

# Configuration
theme:
  name: material
  language: it
  palette:
    scheme: slate
    primary: blue
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/img/redwingbird.png
  search:
    language: en, it
  favicon: assets/img/redwingbird.png
  features:
    - instant
    - tabs

# Extras
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/redwinglabs
extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/extra2.css
extra_javascript:
  - assets/javascripts/extra.js

# Google Analytics
google_analytics:
  - UA-XXXXXXXX-X
  - auto

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
  - toc:
      permalink: false
plugins:
  - search

# Navigation
nav:
  - MOH! Orders:
    - MOH! Orders: 'F&B/MOH!Orders/orders.md'
  - MOH! Services:
    - MOH! Services: 'F&B/MOH!Services/services.md'
  - MOH! Bookings:
    - MOH! Bookings: 'F&B/MOH!Bookings/bookings.md'
  - Impostazioni:
    - Generali: 'F&B/Settings/general.md'
    - Prenotazioni: 'F&B/Settings/reservation.md'
    - Sala: 'F&B/Settings/room.md'
    - Servizio: 'F&B/Settings/service.md'
    - Segmenti: 'F&B/Settings/segment.md'
  - Editor Sala:
    - About Editor Sala: 'F&B/EditorSala/aboutEditorSala.md'
    - Crea Tavolo: 'F&B/EditorSala/createTable.md'
    - Modifica Tavolo: 'F&B/EditorSala/editTable.md'
  - Menu: 
    - Menu: 'F&B/Menu/menu.md'
  - Prenotazioni:
    - Nuova Prenotazione: 'F&B/Reservations/newReservation.md'
    - Modifica Prenotazione: 'F&B/Reservations/editReservation.md'
    - Lista Prenotazioni: 'F&B/ViewReservations/viewReservations.md'
  - Visualizza Tavoli:
    - Tables Manager: 'F&B/ViewTables/viewTables.md'
    - Comanda: 'F&B/ViewTables/order.md'
    - Assegna Sedia: 'F&B/ViewTables/assignChair.md'
  - Cassa: 
    - Cassa: 'F&B/Cash/cash.md'
  - Gestione Conti:
    - Panoramica Gestione Conti: 'F&B/BillsManagement/aboutBillsManagement.md'
    - Lista Conti: 'F&B/BillsManagement/billsList.md'
    - Assegni/Bonifici: 'F&B/BillsManagement/bankCheck&Transfer.md'
    - Chiusure Fiscali: 'F&B/BillsManagement/closingReports.md'
    - Fatture: 'F&B/BillsManagement/invoices.md'
    - PM: 'F&B/BillsManagement/PM.md' 
  - Storico Ordini:
    - Tavoli: 'F&B/Registry/tables.md'
    - Prenotazione: 'F&B/Registry/reservations.md'
  - Cucina:
    - About Kitchen: 'Kitchen/aboutKitchen.md'
    - Sommario Ordini: 'Kitchen/orderSummary.md'
    - Dettaglio Ordini: 'Kitchen/detailedOrder.md'