# Project information
site_name: RWL Documentation
site_description: Documentazione delle app prodotte da RedWingLabs
site_author: RedWing Labs

# Copyright
copyright: Copyright &copy; 2019 - 2020 RWL Srl

# Configuration
theme:
  name: material
  language: it
  palette:
    scheme: default
    primary: blue grey
    accent: red
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/img/redwingbird.png
  search:
    language: en, it
  favicon: assets/img/redwingbird.png
  features:
    - navigation.instant
    - navigation.tabs
    # - toc.integrate

# Extras
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/redwinglabs
extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/extra2.css
extra_javascript:
  - assets/javascripts/extra.js

# Google Analytics
google_analytics:
  - UA-167197052-1
  - auto

# Extensions
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: true
  - pymdownx.critic
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.smartsymbols
  - toc:
      permalink: false
plugins:
  - search

# Navigation
nav:
- Quadro:
  - Quadro: 'index.md'
  - Configura il tuo hotel: 
    - Configura la tua struttura: 'Quadro/Settings/property.md'
    - Servizi Prenotabili: 'Quadro/Settings/stay.md'
    - Servizi Aggiuntivi: 'Quadro/Settings/serv&prod.md'
    - Prodotti: 'Quadro/Settings/products.md'
    - Tariffe: 'Quadro/Settings/rates.md'
    - Cancellation Policy: 'Quadro/Settings/cancellationPolicy.md'
    - Gestione delle Tariffe: 'Quadro/Settings/rateManagement.md'
    - Restrictions: 'Quadro/Settings/restrictions.md'
    - Voucher: 'Quadro/Settings/vouchers.md'
    - Spazi: 'Quadro/Settings/spaces.md'
    - Segmenti: 'Quadro/Settings/segments.md'
    - Dipartimenti ed Impiegati: 'Quadro/Settings/depts&Empl.md'
    - Outlets: 'Quadro/Settings/outlets.md'
    - Placeholder Emails: 'Quadro/Settings/placeholders.md'
    - Contabilità: 'Quadro/Settings/accounting.md'
    - Booking engine: 'Quadro/Settings/bookingEngine.md'
    - Registration Card: 'Quadro/Settings/registrationCard.md'
  - Reservations:
    - New Reservation: 'Quadro/Reservations/reservation.md'
    - Overview: 'Quadro/Reservations/resOverview.md'
    - Timeline: 'Quadro/Reservations/timeline.md'
    - Report: 'Quadro/Reservations/report.md'
  - Profiles:
    - New Customer: 'Quadro/Profiles/newUser.md'
    - Customers: 'Quadro/Profiles/usersList.md'
    - Aziende: 'Quadro/Profiles/companies.md'
    - Contratti per Agenzie di viaggio: 'Quadro/Profiles/travAgencyContracts.md'
  - Distribution:
    - Occupancy: 'Quadro/Distribution/occupancy.md'
    - Availability: 'Quadro/Distribution/availability.md'
    - Rate Management: 'Quadro/Distribution/rateManagement.md'
    - Action Log: 'Quadro/Distribution/actionLog.md'
  - Spaces: 'Quadro/Spaces/spaces.md'
  - Finances:
    - Accounting Ledger: 'Quadro/Finances/accountingLedger.md'
    - Posting Journal: 'Quadro/Finances/postingJournal.md'
    - Billing & Invoices: 'Quadro/Finances/bills&inv.md'
  - Report:
    - Manager: 'Quadro/Report/manager.md'
    - Accounting: 'Quadro/Report/accounting.md'
    - Activity: 'Quadro/Report/activity.md'
    - Product: 'Quadro/Report/product.md'
    - Spent Nights: 'Quadro/Report/spentNight.md'
    - Payment: 'Quadro/Report/payment.md'
  - Task Manager: 'Quadro/TaskManager/task.md'
- FnB: 
  - FnB: 'F&B/intro.md'
  - App Ordini: 'F&B/MOH!Orders/orders.md'
  - App Prenotazioni: 'F&B/MOH!Bookings/bookings.md'
  - Impostazioni:
    - Generali: 'F&B/Settings/general.md'
    - Prenotazioni: 'F&B/Settings/reservation.md'
    - Sala: 'F&B/Settings/room.md'
    - Servizio: 'F&B/Settings/service.md'
    - Segmenti: 'F&B/Settings/segment.md'
    - App Consegna: 'F&B/Settings/moh!Delivery.md'
    - App Asporto: 'F&B/Settings/moh!TakeAway.md'
    - App Servizi: 'F&B/Settings/moh!Services.md'
  - Editor Sala: 'F&B/EditorSala/aboutEditorSala.md'
  - Menu: 'F&B/Menu/menu.md'
  - Prenotazioni:
    - Lista Prenotazioni: 'F&B/Reservations/viewReservations.md'
    - Nuova Prenotazione: 'F&B/Reservations/newReservation.md'
  - Visualizza Tavoli:
    - Tables Manager: 'F&B/ViewTables/viewTables.md'
    - Comanda: 'F&B/ViewTables/order.md'
    - Assegna Sedia: 'F&B/ViewTables/assignChair.md'
  - Cassa: 'F&B/Cash/cash.md'
  - Gestione Conti:
    - Panoramica Gestione Conti: 'F&B/BillsManagement/aboutBillsManagement.md'
    - Lista Conti: 'F&B/BillsManagement/billsList.md'
    - Assegni/Bonifici: 'F&B/BillsManagement/bankCheck&Transfer.md'
    - Chiusure Fiscali: 'F&B/BillsManagement/closingReports.md'
    - Fatture: 'F&B/BillsManagement/invoices.md'
    - PM: 'F&B/BillsManagement/PM.md' 
  - Storico Ordini:
    - Prenotazione: 'F&B/Registry/reservations.md'
  - Cucina:
    - Sommario Ordini: 'Kitchen/orderSummary.md'
    - Dettaglio Ordini: 'Kitchen/detailedOrder.md'